// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_6HGM6R0d2DCvie0yz5ThmD4_KT1PC0U',
    appId: '1:658517710985:web:b9f773d70092faa1e98e58',
    messagingSenderId: '658517710985',
    projectId: 'first-a2f32',
    authDomain: 'first-a2f32.firebaseapp.com',
    databaseURL: 'https://first-a2f32.firebaseio.com',
    storageBucket: 'first-a2f32.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp2FSKVnacSBcsUCw6A5X9U0qvFS8fBAQ',
    appId: '1:658517710985:android:280cc43bff50f00ee98e58',
    messagingSenderId: '658517710985',
    projectId: 'first-a2f32',
    databaseURL: 'https://first-a2f32.firebaseio.com',
    storageBucket: 'first-a2f32.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkY26XtyKQGK8eCA3Eh1y4fMaODk3AtDg',
    appId: '1:658517710985:ios:2cb878c471dc98d8e98e58',
    messagingSenderId: '658517710985',
    projectId: 'first-a2f32',
    databaseURL: 'https://first-a2f32.firebaseio.com',
    storageBucket: 'first-a2f32.firebasestorage.app',
    iosBundleId: 'com.example.tabaani',
  );
}
